### ISSUE TITLE
Mengganti dialogue

### ISSUE THREAD

**Issue by nananganteng** [Shiro-Game-Production/regret-project#10]
Pada bagian dialogue "Yuri : Kenapa di kamar ku ada beginian?" bisa diganti dengan "Yuri : Kenapa di kamar ku ada altar kematian?" dengan alasan karena player merasa bingung dengan kata "beginian". Kata tersebut terlalu rancu sehingga player tidak dapat menebak benda apa yang dimaksud.

**Comment by alfianAH** [comment]
minta tolong dialogue di notionnya di revisi.

**Comment by alfianAH** [comment]
Fixed.
Dialogue di unity sudah di ganti. minta tolong nanti di notion di revisi juga yah.

**Comment by alfianAH** [comment]
Tambahan: untuk interaksi altar, sepertinya bagus kalau tambah sprite foto ken di altar yang menandakan bahwa dia sudah meninggoy. karena dialogue mode itu memblurkan 3D, dan tidak bisa dilihat dengan jelas. Jadi saat interaksi altar, masuk dialogue, manampilkan foto ken, lalu masuk dialogue yuri. Gimana kalau begitu?

**Comment by alfianAH** [comment]
Tambahan (opsional): Kalau yang di atas di acc, mungkin sama halnya ketika masuk kamar adik, sprite altar diperlihatkan didialogue sebelum yuri. (Feature ini mungkin akan sedikit membebankan 2D, tapi sambil menunggu feature camera event yang nice to have itu mungkin bisa jadi opsi)
