### ISSUE TITLE
Button settings

### ISSUE THREAD

**Issue by nananganteng** [Shiro-Game-Production/regret-project#13]
Dikarenakan game kita adalah WebGL, akan lebih baik jika ditambah button setting di pojok kanan atas (seperti button pause) pada 3D Gameplay dan button setting sejajar dengan autoplay/hide pada Dialogue Gameplay. Menurut saya, sepertinya tombol pause tidak terlalu dibutuhkan.

**Comment by alfianAH** [comment]
Settings di pojok kanan atas, terus untuk kembali ke main menu gmana?

**Comment by aldyyyy21** [comment]
Pause button seperti dibutuhkan selama game kita masih berbasis WebGL, alasannya untuk menghindari kekeliruan player saat memaikan prototype dalam keadaan fullscreen agar tidak kembali ke windowed mode. saat testing juga tadi agak repot, karena setiap kali hendak mengakses menu jeda, yang terjadi adalah game kembali ke windowed mode kemudian saya baru bisa mengakses menu jeda dengan syarat kedaan game harus dalam windowed mode.

**Comment by alfianAH** [comment]
Fixed.
Solusi: Pause button di ganti jadi settings. Main menu ada dalam settings.
