### ISSUE TITLE
Menggantung

### ISSUE THREAD

**Issue by nananganteng** [Shiro-Game-Production/regret-project#15]
Setelah disadari, semua sprite yang ada didalam in game "menggantung" termasuk yang ada pada welcome screen dan sangat mengganggu OCD saya.
![gantung](https://user-images.githubusercontent.com/91710593/145192756-97715c38-66b6-43b1-9046-191811a43258.png)

**Comment by alfianAH** [comment]
Fixed. 
Problem: Interactive UI (bekerja baik di Unity tapi ternyata tidak sesuai ekspektasi saat publish)
Solusi: portrait diturunkan
