### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by nananganteng** [Shiro-Game-Production/regret-project#16]
Untuk bagian tutorial, setidaknya player diberi info cara untuk menggerakan player ketika baru pertama kali masuk kedalam 3D Gameplay seperti gambar berikut
![info tutorial](https://user-images.githubusercontent.com/91710593/145193847-8036bacf-4437-4832-80ac-8853a66d7ea1.png)
.

**Comment by alfianAH** [comment]
Sudah di implementasi.
Cek rilis terbaru.
