### ISSUE TITLE
Menu jeda (Option "Lanjutkan")

### ISSUE THREAD

**Issue by aldyyyy21** [Shiro-Game-Production/regret-project#18]
setelah player menekan tombol "Lanjutkan" disaat memaikan dialog gameplay, dialog di text box secara otomatis terganti menjadi dialog selanjutnya.

langkah :
1. buka menu jeda saat memainkan dialog gameplay
2. kemudian tekan tombol "lanjutkan"
3. dialog berubah secara otomatis dimana seharusnya dialog terganti saat melakukan klik di dialog box

**Comment by alfianAH** [comment]
Fixed. Saat dialogue sudah tidak bisa dipause, karena escape key sudah tidak ada dan diganti dengan dengan tombol pause. tombol pause juga sudah tidak bisa di tekan saat dialogue, karena layer dialogue lebih diatas dibanding pause button
