### ISSUE TITLE
Background Dialog gameplay tidak diam

### ISSUE THREAD

**Issue by aldyyyy21** [Shiro-Game-Production/regret-project#20]
saat player memasuki dialog gameplay dan melakukan klik pada dialog box, kamera background karakter 2D ikut bergerak

langkah : 
1. mainkan dialog gameplay
2. klik dialog pada text box
3. dialog terganti dan kamera background karakter ikut bergerak

**Comment by alfianAH** [comment]
Fixed. 
Problem bisa dilihat di #7
