### ISSUE TITLE
pause menu button saat dialog gameplay

### ISSUE THREAD

**Issue by aldyyyy21** [Shiro-Game-Production/regret-project#23]
saat player memasuki dialog gameplay kemudian hendak mengakses pause menu button, pause button berada di balik layer blur sehingga membuat player tidak dapat melakukan klik ke pause button.

langkah : 
1. mainkan dialog gameplay
2. perhatikan pause button berada di balik layer blur sehingga tidak dapat di akses.

**Comment by alfianAH** [comment]
Pause di ganti menjadi settings
