### ISSUE TITLE
Animasi Freeze

### ISSUE THREAD

**Issue by togipology** [Shiro-Game-Production/regret-project#24]
1. Animasi tidak berlangsung lama, saat di klik berkali kali dan karakter berjalan, animasi hanya berlangsung beberapa detik, selanjutnya animasi berhenti dan karakter akan berpindah tempat tanpa adanya animasi.

2. Animasi idle harusnya terdapat gerakan bernapas namun sekarang hanya terdiam beku

**Comment by alfianAH** [comment]
Fixed
Problem: Dikarenakan animasi dari FBX tidak loop dan kemungkinan karena perubahan file FBX menyebabkan loop nya yang sebelumnya di set hilang.
Solusi: Loop di set kembali ke animasi yuri dari Unity.
