### ISSUE TITLE
Interaction button diklik berkali-kali

### ISSUE THREAD

**Issue by alfianAH** [Shiro-Game-Production/regret-project#27]
Klaau interaction button diklik berkali-kali, player tidak sampai pada tujuan yang diinginkan

**Comment by aryuz404** [comment]
solusi sama dengan #29

**Comment by alfianAH** [comment]
Fixed.
Solution: Membuat interaction button hanya bisa di klik satu kali saat player memasuki trigger.
Kasus khusus ketika membuka pintu, membuat interaction button tidak bisa diakses selama door animation masih berjalan.
