### ISSUE TITLE
Sfx Pintu terbuka bug

### ISSUE THREAD

**Issue by aldyyyy21** [Shiro-Game-Production/regret-project#28]
saat pintu di buka berkali-kali ketika player hendak keluar dari rumah, suara pintu tertutup melakukan repeat beberapa kali. untuk video ada di link dibawah ini :

link : https://www.notion.so/Test-Case-video-vault-1c5ad3626c08473fb68f4d99cbbd6fe0

**Comment by aryuz404** [comment]
solusi sama dengan #29

**Comment by alfianAH** [comment]
Solusi sama dengan #27
