### ISSUE TITLE
Bug Frozen notif pintu terkunci

### ISSUE THREAD

**Issue by aldyyyy21** [Shiro-Game-Production/regret-project#29]
notice pintu terkunci tidak hilang setelah pintu yang terkunci di interact berkali-kali.

Berikut video dokumentasinya : 
https://www.notion.so/Test-Case-video-vault-1c5ad3626c08473fb68f4d99cbbd6fe0

**Comment by aryuz404** [comment]
ketika tombol interaktif diklik, hilangkan tombol interaksinya

**Comment by alfianAH** [comment]
Solusi sama dengan #27
