### ISSUE TITLE
Player Movement

### ISSUE THREAD

**Issue by alfianAH** [Shiro-Game-Production/regret-project#32]
Ketika player mengklik object maka player pindah ke tempat lain bukan ke objectnya. 

Solusi: mungkin tambahin collider di object.

**Comment by aryuz404** [comment]
tambahin collider di tiap object, bisa pakai box collider atau mesh collider

**Comment by aryuz404** [comment]
Fixed.
Solusi : menambahkan box collider dan mesh collider ke tiap object
