### ISSUE TITLE
Bug Dialog dapat di lanjutkan saat mengakses menu pengaturan

### ISSUE THREAD

**Issue by aldyyyy21** [Shiro-Game-Production/regret-project#36]
di saat player mengakses menu pengaturan bersamaan dengan gameplay dialog, player tetap bisa melanjutkan dialog di setiap player melakukan klik pada interface menu pengaturan.

langkah untuk menemukan bug : 
1. mainkan dialog gameplay (monolog yuri, atau dialog dengan rin mama dan ken)
2. buka menu pengaturan
3. klik di sembarang tempat atau lakukan interaksi dengan tombol atau slider di menu pengaturan
4. dialog tetap berlanjut di background

Documentation Link : 
https://www.notion.so/Test-Case-video-vault-1c5ad3626c08473fb68f4d99cbbd6fe0

**Comment by aryuz404** [comment]
Bikin 2 metode di DialogueManager, PauseMode dan ContinueMode. PauseMode mengambil metode PushDialogMode ke pause. ContinueMode mengambil metode PopDialogMode ke pause
