### ISSUE TITLE
Tampilan Prompt yang bertumpuk dengan Interface menu pengaturan

### ISSUE THREAD

**Issue by aldyyyy21** [Shiro-Game-Production/regret-project#37]
Untuk prompt kembali ke menu awal sebaiknya tidak di buka bersamaan dengan menu pengaturan agar tampilannya tidak terlihat bertumpuk.

1. buka menu pengaturan
2. pilih tombol beranda

**Comment by aryuz404** [comment]
Menambahkan metode HidePrompt pada MainMenu Button untuk menghide SettingPrompt saat membuka prompt untuk kembali ke menu awal
