### ISSUE TITLE
Bug Item Interaction (kalender, buku nikah, dan brankas)

### ISSUE THREAD

**Issue by aldyyyy21** [Shiro-Game-Production/regret-project#38]
Paper dialog box akan muncul ketika melakukan interaksi item secara berkali-kali

1. mainkan 3d gameplay
2. cari item yang bisa di interaksikan
3. lakukan iteraksi secara beruntun
4. paper dialog box akan muncul dan hanya bisa di tutup ketika player mentrigger dialog event

documentation link : https://www.notion.so/Test-Case-video-vault-1c5ad3626c08473fb68f4d99cbbd6fe0

**Comment by alfianAH** [comment]
Fix. 
Solusi: Membut boolean dialogue is playing true di parameter after effect fade in
